### ISSUE TITLE
1.19 - Warden spawning caused a crash?

### ISSUE THREAD

**Issue by somebirby** [PepperCode1/Continuity#109]
Here's the crash report:
[crash-2022-06-08_18.12.13-client.txt](https://github.com/PepperCode1/Continuity/files/8863366/crash-2022-06-08_18.12.13-client.txt)

And the what showed up in the logs :
```
[18:12:13] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1567) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1315) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1143) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19) ~[continuity-2.0.0+1.19.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70) ~[continuity-2.0.0+1.19.jar:?]
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10) ~[continuity-2.0.0+1.19.jar:?]
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305) ~[?:?]
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
	at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18) ~[continuity-2.0.0+1.19.jar:?]
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16) ~[continuity-2.0.0+1.19.jar:?]
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10) ~[continuity-2.0.0+1.19.jar:?]
	at net.minecraft.class_901.handler$zdl000$beforeRenderModel(class_901.java:518) ~[client-intermediary.jar:?]
	at net.minecraft.class_901.method_3965(class_901.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_901.method_3936(class_901.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:141) ~[client-intermediary.jar:?]
	... 10 more
```

**Comment by PepperCode1** [comment]
Install Indium.
