### ISSUE TITLE
Crash in 1.19 (I don't know why)

### ISSUE THREAD

**Issue by Lolothepro** [PepperCode1/Continuity#145]
```
[12:26:45] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1567) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.redirect$zde000$redirectRenderEntity(class_761.java:5358) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1315) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.redirect$zdc000$redirectRenderingWorld(class_757.java:2150) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1143) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.1-beta.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19) ~[continuity-2.0.0+1.19.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70) ~[continuity-2.0.0+1.19.jar:?]
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10) ~[continuity-2.0.0+1.19.jar:?]
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305) ~[?:?]
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
	at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18) ~[continuity-2.0.0+1.19.jar:?]
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16) ~[continuity-2.0.0+1.19.jar:?]
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10) ~[continuity-2.0.0+1.19.jar:?]
	at net.minecraft.class_901.handler$zkj000$beforeRenderModel(class_901.java:518) ~[client-intermediary.jar:?]
	at net.minecraft.class_901.method_3965(class_901.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_901.method_3936(class_901.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:141) ~[client-intermediary.jar:?]
	... 25 more
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 7/24/22, 12:26 PM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zkj000$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.redirect$zde000$redirectRenderEntity(class_761.java:5358)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$zdc000$redirectRenderingWorld(class_757.java:2150)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zkj000$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.redirect$zde000$redirectRenderEntity(class_761.java:5358)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$zdc000$redirectRenderingWorld(class_757.java:2150)

-- Entity being rendered --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
	Entity ID: 1704
	Entity Name: Bloc soumis à la gravité
	Entity's Exact location: 17.50, 41.00, 54.50
	Entity's Block location: World: (17,41,54), Section: (at 1,9,6 in 1,2,3; chunk contains blocks 16,0,48 to 31,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Immitating BlockState: Block{minecraft:gravel}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.redirect$zde000$redirectRenderEntity(class_761.java:5358)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$zdc000$redirectRenderingWorld(class_757.java:2150)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_901@41a9920d
	Location: -58.84,-19.63,13.83 - World: (-59,-20,13), Section: (at 5,12,13 in -4,-2,0; chunk contains blocks -64,0,0 to -49,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 0.0
	Delta: 0.4000404
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.redirect$zde000$redirectRenderEntity(class_761.java:5358)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$zdc000$redirectRenderingWorld(class_757.java:2150)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Affected level --
Details:
	All players: 1 total; [class_746['Lolothepro29'/193, l='ClientWorld minecraft:the_nether', x=76.34, y=59.01, z=40.67]]
	Chunk stats: Client Chunks (ImmPtl) 729
	Level dimension: minecraft:the_nether
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2239 game time, 2239 day time
	Server brand: quilt
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, lambdabettergrass/default

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.18.0-13.1-liquorix-amd64
	Java Version: 17.0.3.1, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), BellSoft
	Memory: 318250376 bytes (303 MiB) / 2248146944 bytes (2144 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: GP104 [GeForce GTX 1070]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16064.52
	Virtual memory used (MB): 16945.79
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 2697.50
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Loaded Shaderpack: (off)
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		architectury: Architectury 5.10.33
		awesomedungeon: Awesome Dungeon 2.0.11
		awesomedungeonend: Awesome Dungeon Edition end 1.0.3
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.3
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.8
		cem: Custom Entity Models 0.7.1
		citresewn: CIT Resewn 1.1.1+1.19
		citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config: Cloth Config v6 7.0.73
		completeconfig-base: completeconfig-base 2.0.0-beta.3
		completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		continuity: Continuity 2.0.0+1.19
		cullleaves: Cull Leaves 2.3.4
		fallingleaves: Falling Leaves 1.12.1+1.19
		identity: Identity 2.5.0-1.19
		imm_ptl_core: Immersive Portals Core 2.0.5
		immersive_portals: Immersive Portals 2.0.5
		iris: Iris 1.2.5
		java: OpenJDK 64-Bit Server VM 17
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		libraryferret: Library Ferret 2.0.0
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.4
		q_misc_util: QMiscUtil 2.0.5
		quilt_advancement: Quilt Advancement API 2.0.0-beta.16+1.19
		quilt_base: Quilt Base API 2.0.0-beta.16+1.19
		quilt_biome: Quilt Biome API 2.0.0-beta.16+1.19
		quilt_block_entity: Quilt Block Entity API 2.0.0-beta.16+1.19
		quilt_block_extensions: Quilt Block Extensions API 2.0.0-beta.16+1.19
		quilt_client_command: Quilt Client Command API 2.0.0-beta.16+1.19
		quilt_command: Quilt Command API 2.0.0-beta.16+1.19
		quilt_crash_info: Quilt Crash Info 2.0.0-beta.16+1.19
		quilt_dimension: Quilt Dimension API 2.0.0-beta.16+1.19
		quilt_item_content_registry: Quilt Item Content Registry API 2.0.0-beta.16+1.19
		quilt_item_group: Quilt Item Group API 2.0.0-beta.16+1.19
		quilt_item_setting: Quilt Item Setting API 2.0.0-beta.16+1.19
		quilt_lifecycle_events: Quilt Lifecycle Events 2.0.0-beta.16+1.19
		quilt_loader: Quilt Loader 0.17.1-beta.6
		quilt_networking: Quilt Networking 2.0.0-beta.16+1.19
		quilt_recipe: Quilt Recipe API 2.0.0-beta.16+1.19
		quilt_registry: Quilt Registry API 2.0.0-beta.16+1.19
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 2.0.0-beta.16+1.19
		quilt_resource_loader: Quilt Resource Loader 2.0.0-beta.16+1.19
		quilt_screen: Quilt Screen API 2.0.0-beta.16+1.19
		quilt_tags: Quilt Tags API 2.0.0-beta.16+1.19
		quilt_tooltip: Quilt Tooltip API 2.0.0-beta.16+1.19
		quilted_fabric_api: Quilted Fabric API 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_api_base: Quilted Fabric API Base 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_command_api_v2: Quilted Fabric Command API (v2) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_data_generation_api_v1: Quilted Fabric Data Generation API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_message_api_v1: Quilted Fabric Message API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 2.0.0-beta.9+0.58.0-1.19
		roughlyenoughitems: Roughly Enough Items 9.1.517
		sodium: Sodium 0.4.2+build.16
		spruceui: SpruceUI 4.0.0+1.19
		starlight: Starlight 1.1.1+fabric.ae22326
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 515.57, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: lambdabettergrass/default
	Current Language: Français (France)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor
	Server Running: true
	Player Count: 1 / 8; [class_3222['Lolothepro29'/193, l='ServerWorld minecraft:the_nether Test', x=76.34, y=59.01, z=40.67]]
	Data Packs: vanilla
	World Generation: Experimental
#@!@# Game crashed! Crash report saved to: #@!@# /mnt/76561DD3561D94C9/MultiMC/instances/Identity1/.minecraft/crash-reports/crash-2022-07-24_12.26.45-client.txt
```

**Comment by TheLimeGlass** [comment]
Reproduced the error on 3.0.0.beta4 1.20.1 reopen?

**Comment by YukiAyase** [comment]
> Reproduced the error on 3.0.0.beta4 1.20.1 reopen?

### **Please avoid necroing old threads and create your own one providing your own log file**
