### ISSUE TITLE
[1.18.2 Major Bug] Continuty + Creat 0.5c causes infinite load

### ISSUE THREAD

**Issue by itsdinkd** [PepperCode1/Continuity#156]
After updating create to 0.5c in fabric, continuity prevents loading Another Quality Modpack 2.

https://pastebin.com/c07GufpG
```java
[10:44:28] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalStateException: BlockModel parent has to be a block model.
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalStateException: BlockModel parent has to be a block model.
	at net.minecraft.client.render.model.json.JsonUnbakedModel.getTextureDependencies(JsonUnbakedModel:180) ~[?:?]
	at net.minecraft.client.render.model.json.WeightedUnbakedModel.method_3498(WeightedUnbakedModel:65) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.client.render.model.json.WeightedUnbakedModel.getTextureDependencies(WeightedUnbakedModel:65) ~[?:?]
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.lambda$wrapCTMModels$0(ModelWrappingHandler.java:56) ~[continuity-2.0.0+1.18.2.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.wrapCTMModels(ModelWrappingHandler.java:51) ~[continuity-2.0.0+1.18.2.jar:?]
	at net.minecraft.client.render.model.ModelLoader.handler$fem000$onFinishAddingModels(ModelLoader:4656) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.<init>(ModelLoader:217) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:52) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:19) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18791(SinglePreparationResourceReloader:11) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
	```

**Comment by PepperCode1** [comment]
Did you test to see if the issue is resolved and the game fully works if Continuity is removed?

**Comment by itsdinkd** [comment]
Testing now

**Comment by itsdinkd** [comment]
Still occurs, so its not continuity. 

```java
[11:20:58] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.equals(Object)" because "this.field_21770" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.equals(Object)" because "this.field_21770" is null
	at net.minecraft.client.util.SpriteIdentifier.equals(SpriteIdentifier:62) ~[?:?]
	at java.util.HashMap.putVal(HashMap.java:633) ~[?:?]
	at java.util.HashMap.put(HashMap.java:610) ~[?:?]
	at java.util.HashSet.add(HashSet.java:221) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.<init>(ModelLoader:219) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:52) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:19) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18791(SinglePreparationResourceReloader:11) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
	```
	
	Closing ticket
