### ISSUE TITLE
Game crashes whenever gravel fallss

### ISSUE THREAD

**Issue by mei1012** [PepperCode1/Continuity#202]
For some reason my game crashes whenever I make gravel fall?

Steps to reproduce:
1. Use Continuity
2. Make a gravel tower
3. Break the first block making it fall
4. Crash?

[Here is the crash report](https://crashy.net/I3PIeo6AFI8YoMe5UL5F)

Full Crash Report:

```
---- Minecraft Crash Report ----
// My bad.

Time: 1/8/23, 6:15 PM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.client.render.entity.FallingBlockEntityRenderer.handler$zcg000$beforeRenderModel(FallingBlockEntityRenderer:518)
	at net.minecraft.client.render.entity.FallingBlockEntityRenderer.render(FallingBlockEntityRenderer:45)
	at net.minecraft.client.render.entity.FallingBlockEntityRenderer.render(FallingBlockEntityRenderer:17)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:141)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1567)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1315)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1039)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:816)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1143)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zcg000$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Entity being rendered --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
	Entity ID: 29698
	Entity Name: Falling Block
	Entity's Exact location: 208.50, 65.00, -49.50
	Entity's Block location: World: (208,65,-50), Section: (at 0,1,14 in 13,4,-4; chunk contains blocks 208,-64,-64 to 223,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AABB:[208.00999999046326d,65.0d,-49.99000000953674d,208.99000000953674d,65.98000001907349d,-49.00999999046326d],Air:300s,BlockState:{Name:"minecraft:gravel"},DropItem:1b,FallDistance:0.0f,FallHurtAmount:0.0f,FallHurtMax:40,Fire:-1s,HurtEntities:0b,Invulnerable:0b,Motion:[0.0d,0.0d,0.0d],OnGround:0b,PortalCooldown:0,Pos:[208.5d,65.0d,-49.5d],Rotation:[0.0f,0.0f],Time:0,UUID:[I;-1748004636,853230893,-1120193657,-2123477481]}
	Immitating BlockState: Block{minecraft:gravel}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_901@47b0cd2a
	Location: -0.86,0.38,-2.93 - World: (-1,0,-3), Section: (at 15,0,13 in -1,0,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Rotation: 0.0
	Delta: 0.8000066
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['MEI1012'/29616, l='ClientLevel', x=209.36, y=63.00, z=-46.57]]
	Chunk stats: 1024, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,66,0), Section: (at 0,2,0 in 1,4,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2181056 game time, 2299386 day time
	Server brand: Purpur
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, rotrBLOCKS V33 256x.zip, rotrBLOCKS ITEM V33 256x.zip, rotrBLOCKS DESIGN V33 256x.zip, rotrBLOCKS FLORA V33 256x.zip, rotrBLOCKS DUNGEONS V33 256x.zip, Round-Trees-7.0-1.19+.zip, Slightly-Improved-Font-1.0.0.zip, 0357617007c759c977d5c955b899779f5f24352b

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 427651360 bytes (407 MiB) / 1444937728 bytes (1378 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2756
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 38092.84
	Virtual memory used (MB): 22614.66
	Swap memory total (MB): 5376.00
	Swap memory used (MB): 220.51
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		ambientenvironment: Ambient Environment 8.0+1
		appleskin: AppleSkin 2.4.1+mc1.19
			cloth-config: Cloth Config v6 7.0.65
				cloth-basic-math: cloth-basic-math 0.6.1
		bcc: BetterCompatibilityChecker fabric-2.0.1-build.15
		betteradvancements: Better Advancements 0.2.2.136
		bettermounthud: Better Mount HUD 1.1.4
		betterthirdperson: Better Third Person 1.8.1
		bookshelf: Bookshelf 14.2.10
		capes: Capes 1.4.5+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		chat_heads: Chat Heads 0.6.0
		clumps: Clumps 9.0.0+7
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+3
		cpm: Customizable Player Models 0.6.3a
		craftpresence: CraftPresence 1.8.9
		creativecore: CreativeCore (Fabric) 2.8.5
		cullleaves: Cull Leaves 3.0.1
			midnightlib: MidnightLib 1.0.0
		debugify: Debugify 2.3.2
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		emotecraft: Emotecraft 2.2.7-b.build.47
			bendy-lib: Bendy api 2.1.3-test2
			player-animator: Player Animator 0.4.0
		enchdesc: EnchantmentDescriptions 11.1.9
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.7
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		forcecloseloadingscreen: kennytv's epic force close loading screen mod for Fabric 1.1.1
		fpsreducer: FPS Reducer 1.19.2-2.1
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.4
		musicplayer: Music Player 2.4.0.12
		ngroklan: Ngrok LAN 1.4.4-1.19
			blue_endless_jankson: jankson 1.2.1
			com_github_alexdlaird_java-ngrok: java-ngrok 1.5.6
			org_yaml_snakeyaml: snakeyaml 1.8
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		perspectivemod: Perspective Mod Redux 0.0.5_01
		physicsmod: Physics Mod 2.8.0
		preciseblockplacing: PreciseBlockPlacing 2.0.0
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		starlight: Starlight 1.1.1+fabric.ae22326
		uteamcore: U Team Core 4.0.0.4
		xaerobetterpvp: Better PVP Mod 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
		zoomify: Zoomify 2.9.0
			com_github_llamalad7_mixinextras: mixinextras 0.1.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.5
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.5
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.5
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.5
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.12-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 527.56, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/rotrBLOCKS V33 256x.zip (incompatible), file/rotrBLOCKS ITEM V33 256x.zip (incompatible), file/rotrBLOCKS DESIGN V33 256x.zip (incompatible), file/rotrBLOCKS FLORA V33 256x.zip (incompatible), file/rotrBLOCKS DUNGEONS V33 256x.zip (incompatible), file/Round-Trees-7.0-1.19+.zip, file/Slightly-Improved-Font-1.0.0.zip (incompatible)
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Continuity (continuity)
```

**Comment by PepperCode1** [comment]
Duplicate of #107; Install Indium.
