### ISSUE TITLE
Fabric 1.19.4 Crash due to falling blocks(?)

### ISSUE THREAD

**Issue by Owehttamy** [PepperCode1/Continuity#234]
```---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-03-30 18:52:38
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zgh000$continuity$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1572)
	at net.minecraft.class_761.method_22710(class_761.java:1322)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zgh000$continuity$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1572)
	at net.minecraft.class_761.method_22710(class_761.java:1322)
	at net.minecraft.class_757.method_3188(class_757.java:1100)

-- Entity being rendered --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
	Entity ID: 781
	Entity Name: Falling Gravel
	Entity's Exact location: -3295.50, 57.96, -2076.50
	Entity's Block location: World: (-3296,57,-2077), Section: (at 0,9,3 in -206,3,-130; chunk contains blocks -3296,-64,-2080 to -3281,319,-2065), Region: (-7,-5; contains chunks -224,-160 to -193,-129, blocks -3584,-64,-2560 to -3073,319,-2049)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Immitating BlockState: Block{minecraft:gravel}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1572)
	at net.minecraft.class_761.method_22710(class_761.java:1322)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_901@5227226c
	Location: -169.87,-91.09,87.53 - World: (-170,-92,87), Section: (at 6,4,7 in -11,-6,5; chunk contains blocks -176,-64,80 to -161,319,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Rotation: 0.0
	Delta: 0.90000427
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1572)
	at net.minecraft.class_761.method_22710(class_761.java:1322)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Owehttamy'/120, l='ClientLevel', x=-3125.62, y=147.44, z=-2163.97]]
	Chunk stats: 1024, 504
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,116,0), Section: (at 0,4,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 27078 game time, 27078 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/§2§lOwehttamy's§0-§a§lSMP§0-§2§lPack+§0-§7§o1.2§0-§8, file/[Carpentry] Better Interior, minecraft/supporteatinganimation, essential

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2859703520 bytes (2727 MiB) / 4362076160 bytes (4160 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37566.04
	Virtual memory used (MB): 19056.35
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		animatica: Animatica 0.5+1.19
		appleskin: AppleSkin 2.4.3+mc1.19.4
		architectury: Architectury 8.1.75
		blur: Blur (Fabric) 3.0.0
			midnightlib: MidnightLib 1.2.1
			satin: Satin 1.11.0
		boostedbrightness: Boosted Brightness 2.1.3
		borderlessmining: Borderless Mining 1.1.7+1.19.4
		chat_heads: Chat Heads 0.10.9
		chathighlighter: ChatHighlighter 1.0.1+mc1.19.3
		chunky: Chunky 1.3.53
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		cleardespawn: Clear Despawn 1.1.10
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.2+1.19.3
		cullleaves: Cull Leaves 3.0.3
		detailab: Detail Armor Bar 2.6.3+1.19.4-fabric
		eatinganimationid: Eating Animation 1.9.3
		elementa: Elementa 578
		entity_texture_features: Entity Texture Features 4.3.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		essential: Essential 12168+deploy-staging+g5c9691d52
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		fabric-api: Fabric API 0.76.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.25+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.4+ae0966baf4
			fabric-commands-v0: Fabric Commands (v0) 0.2.42+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.52+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.7+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.5+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.3+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.25+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.29+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.37+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.22+ca5f59aaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.39+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.1+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.6+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.2+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+938a1d56f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.18+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.0.1+9003cbe9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.17
		fabrishot: Fabrishot 1.9.1
		fallingleaves: Falling Leaves 1.15.0+1.19.4
		inventoryprofilesnext: Inventory Profiles Next 1.9.4
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.0+1.19.4
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 4.2.0+1.19.4
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 2.0.4
		lightoverlay: Light Overlay 7.0.2
		lithium: Lithium 0.11.1
		lod: Distant Horizons 1.6.11a
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.1.0-rc.4
		moreculling: More Culling 1.19.4-0.17.0
			conditional-mixin: conditional mixin 0.3.2
		no_fog: No Fog 1.3.3+1.16.5-1.19.4
		notenoughanimations: NotEnoughAnimations 1.6.3
		org_jetbrains_annotations: annotations 13.0
		raised: Raised 1.2.2
		shulkerboxtooltip: Shulker Box Tooltip 3.2.5+1.19.4
		skinlayers: 3d Skin Layers 1.5.3-mc1.19.4
		smoothboot: Smooth Boot 1.19.4-1.7.0
		smoothswapping: Smooth Swapping 0.8
		sodium: Sodium 0.4.10+build.24
		sound_physics_remastered: Sound Physics Remastered 1.19.4-1.1.0
		starlight: Starlight 1.1.1+fabric.ae22326
		ukulib: ukulib 0.6.1+1.19.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		universalcraft: UniversalCraft 262
		vcinteraction: Voice Chat Interaction 1.19.4-1.0.3
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.4.0+1.19.4
		vigilance: Vigilance 278
		visuality: Visuality 0.7.0
		voicechat: Simple Voice Chat 1.19.4-2.3.28
		worldedit: WorldEdit 7.2.13+46576cc
		yet-another-config-lib: YetAnotherConfigLib 2.3.1
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.17-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.49, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/§2§lOwehttamy's§0-§a§lSMP§0-§2§lPack+§0-§7§o1.2§0-§8, file/[Carpentry] Better Interior, minecraft:supporteatinganimation
	Current Language: en_us
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Owehttamy'/120, l='ServerLevel[Testing World Generation]', x=-3125.62, y=147.44, z=-2163.97]]
	Data Packs: vanilla, fabric, file/Terralith_1.19.4_v2.3.7b.zip, file/dungeon-now-loading-17-1.19.3.zip (incompatible), file/geophilic‐1.19.4-2.0.0.zip, file/vanilla_parity_2.3.0.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental```

**Comment by PepperCode1** [comment]
Install Indium.
