### ISSUE TITLE
3.0.0-beta.2+1.19.3 is incompatible with Fabric API 0.81.0+ and Indium 1.0.18+

### ISSUE THREAD

**Issue by MelchiorGaspar** [PepperCode1/Continuity#253]
ok I recently updated to mc-v1.19.4 and mods updated.
using [continuity-3.0.0-beta.2+1.19.4.jar]

After I login to [play.manacube.com] server, I choose to load the survival MP map/server.
ManaCube uses its own server resourcepack.

I get the following error:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-05-21 19:26:09
Description: Tessellating block in world - Indigo Renderer

java.lang.NoSuchMethodError: 'net.fabricmc.fabric.api.renderer.v1.material.BlendMode net.fabricmc.fabric.impl.client.indigo.renderer.RenderMaterialImpl.blendMode(int)'
	at me.pepperbell.continuity.client.util.RenderUtil.lambda$createBlendModeGetter$3(RenderUtil.java:80)
	at me.pepperbell.continuity.client.util.RenderUtil.getBlendMode(RenderUtil.java:97)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel$EmissiveBlockQuadTransform.transform(EmissiveBakedModel.java:142)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractRenderContext.lambda$new$1(AbstractRenderContext.java:35)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:48)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.renderQuad(AbstractQuadRenderer.java:68)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:112)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:102)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:46)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:63)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:46)
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:53)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:46)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:71)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:117)
	at net.minecraft.class_846$class_851$class_4578.redirect$zic000$fabric-renderer-indigo$hookChunkBuildTesselate(class_846.java:786)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:578)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:489)
	at net.minecraft.class_846.method_22757(class_846.java:140)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

ERROR LOG attached:
[crash-2023-05-21_19.26.09-client.txt](https://github.com/PepperCode1/Continuity/files/11525793/crash-2023-05-21_19.26.09-client.txt)

**Comment by MelchiorGaspar** [comment]
sorry about the title of this error report.. its not the most helpful. :(

**Comment by MelchiorGaspar** [comment]
I removed/deleted this mod from the mods folder and my MC-v1.19.4 java client works again on the ManaCube server.

**Comment by PepperCode1** [comment]
This is an incompatibility with Fabric API 0.81.0 or newer. It will be fixed soon.

**Comment by MelchiorGaspar** [comment]
Oooh ok ty. 
You can close this when fixed.

**Comment by PepperCode1** [comment]
I have just released 3.0.0-beta.3 for 1.19.3, 1.19.4, and 1.20.1 that have fixed this incompatibility. Note that the 1.19.4 and 1.20.1 versions require Fabric API >=0.86.0, which is currently the latest version.

**Comment by MelchiorGaspar** [comment]
ty so much @PepperCode1 for the fix :D

**Comment by velnias75** [comment]
Sadly the bug **exists still** with the current [Misa Resource Pack](https://www.curseforge.com/minecraft/texture-packs/misas-realistic/files/4777688) and with Version `3.0.0-beta.4` for `1.20.1` 😿

**Comment by YukiAyase** [comment]
> Sadly the bug **exists still** with the current [Misa Resource Pack](https://www.curseforge.com/minecraft/texture-packs/misas-realistic/files/4777688) and with Version `3.0.0-beta.4` for `1.20.1` 😿

**Please avoid necroing old threads, if you have any issues, open up a new thread**
