### ISSUE TITLE
Could not initialize class EmissiveBakedModel on my server resource pack.

### ISSUE THREAD

**Issue by VergilPrime** [PepperCode1/Continuity#278]
Resourcepack created by ItemsAdder
Minecraft 1.20.1
Modlist:
![image](https://github.com/PepperCode1/Continuity/assets/1651211/06aadad7-cea0-48b0-9930-ed4ba23d8fc1)

`java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class me.pepperbell.continuity.client.model.EmissiveBakedModel
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class me.pepperbell.continuity.client.model.EmissiveBakedModel
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.wrap(ModelWrappingHandler.java:43) ~[continuity-3.0.0-beta.2+1.20.jar:?]
	at net.minecraft.class_1088$class_7778.localvar$zbl000$continuity$modifyBakedModel(class_1088.java:548) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_807.method_4753(class_807.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_816.method_4753(class_816.java:89) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Worker-Main-8"]
	at me.pepperbell.continuity.client.util.RenderUtil.lambda$static$0(RenderUtil.java:30) ~[continuity-3.0.0-beta.2+1.20.jar:?]
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305) ~[?:?]
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
	at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
	at me.pepperbell.continuity.client.util.RenderUtil.getMaterialFinder(RenderUtil.java:42) ~[continuity-3.0.0-beta.2+1.20.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.<clinit>(EmissiveBakedModel.java:35) ~[continuity-3.0.0-beta.2+1.20.jar:?]
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.wrap(ModelWrappingHandler.java:43) ~[continuity-3.0.0-beta.2+1.20.jar:?]
	at net.minecraft.class_1088$class_7778.localvar$zbl000$continuity$modifyBakedModel(class_1088.java:548) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_807.method_4753(class_807.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_816.method_4753(class_816.java:89) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 6 more`

**Comment by PepperCode1** [comment]
Please provide the full log.

**Comment by PepperCode1** [comment]
There has been no response so I will provide my best assumed solution. Though the error is potentially unusual, Indium is not present in the mod list, which is required when using Sodium. Duplicate of #107.
