### ISSUE TITLE
He and reeses_sodium_options caused the client to flashback

### ISSUE THREAD

**Issue by aml2023529** [PepperCode1/Continuity#298]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-08-09 12:01:30
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_835.handler$zgc000$continuity$beforeRenderModels(class_835.java:518)
	at net.minecraft.class_835.method_3576(class_835.java:39)
	at net.minecraft.class_835.method_3569(class_835.java:20)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:308)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:271)
	at net.minecraft.class_761.handler$cda000$sodium$onRenderTileEntities(class_761.java:11599)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_835.handler$zgc000$continuity$beforeRenderModels(class_835.java:518)
	at net.minecraft.class_835.method_3576(class_835.java:39)
	at net.minecraft.class_835.method_3569(class_835.java:20)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:308)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:271)
	at net.minecraft.class_761.handler$cda000$sodium$onRenderTileEntities(class_761.java:11599)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Block Entity Details --
Details:
	Name: minecraft:piston // net.minecraft.class_2669
	Block: Block{minecraft:moving_piston}[facing=west,type=normal]
	Block location: World: (-1602,245,1215), Section: (at 14,5,15 in -101,15,75; chunk contains blocks -1616,0,1200 to -1601,255,1215), Region: (-4,2; contains chunks -128,64 to -97,95, blocks -2048,0,1024 to -1537,255,1535)
	Block: Block{minecraft:moving_piston}[facing=west,type=normal]
	Block location: World: (-1602,245,1215), Section: (at 14,5,15 in -101,15,75; chunk contains blocks -1616,0,1200 to -1601,255,1215), Region: (-4,2; contains chunks -128,64 to -97,95, blocks -2048,0,1024 to -1537,255,1535)
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:308)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:271)
	at net.minecraft.class_761.handler$cda000$sodium$onRenderTileEntities(class_761.java:11599)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

-- Affected level --
Details:
	All players: 2 total; [class_746['Ami_donkey'/356435, l='ClientLevel', x=-1604.39, y=247.00, z=1216.74], class_745['Au33s'/20573, l='ClientLevel', x=-1604.39, y=247.00, z=1216.74]]
	Chunk stats: 1024, 28
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,59,0), Section: (at 0,11,0 in 0,3,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 75354169 game time, 75354169 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/[1.19.1]MASA全家桶汉化包.zip, high_contrast

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 230599776 bytes (219 MiB) / 796917760 bytes (760 MiB) up to 6874464256 bytes (6556 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 5GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c04
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24233.55
	Virtual memory used (MB): 13640.60
	Swap memory total (MB): 7936.00
	Swap memory used (MB): 77.80
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx6553m
	Fabric Mods: 
		alternate-current: Alternate Current 1.7.0
		ambientsounds: Ambient Sounds (Fabric) unspecified
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		balm-fabric: Balm 7.0.7
		betterbeds: Better Beds 1.3.0
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.3+1.20.1
		creativecore: CreativeCore 2.10.28
			net_minecraftforge_eventbus: eventbus 6.0.3
		cull-less-leaves: Cull Less Leaves 1.2.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		dashloader: DashLoader 5.0.0-beta.1+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		entity_texture_features: Entity Texture Features 4.5.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.5+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		fpsreducer: FPS Reducer 1.20-2.5
		ibeeditor: IBE Editor 2.2.3
		inventoryprofilesnext: Inventory Profiles Next 1.10.3
		iris: Iris 1.6.5
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.4.3
		java: Java HotSpot(TM) 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 3.0.2
		litematica: Litematica 0.15.0
		malilib: MaLiLib 0.16.0
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.1
		moonlight: Moonlight 1.20-2.7.2
		netherportalfix: NetherPortalFix 13.0.0
		reeses-sodium-options: Reese's Sodium Options 1.6.4+mc1.20.1-build.94
		roughlyenoughitems: Roughly Enough Items 12.0.625
			error_notifier: Error Notifier 1.0.9
		sodium: Sodium 0.5.0
		sodium-extra: Sodium Extra 0.5.0+mc1.20.1-build.111
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.2+fabric.dbc156f
		tiefix: TieFix 1.14.0
		xaeroworldmap: Xaero's World Map 1.32.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20.1-Fabric
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1060 5GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1920x1057
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla, fabric, file/[1.19.1]MASA全家桶汉化包.zip (incompatible), high_contrast
	Current Language: zh_cn
	CPU: 6x Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz

**Comment by hexadecimal233** [comment]
安装一下[Indium](https://modrinth.com/mod/indium)
还有DashLoader暂不兼容Sodium0.5.0

**Comment by YukiAyase** [comment]
> 安装一下[Indium](https://modrinth.com/mod/indium) 还有DashLoader暂不兼容Sodium0.5.0

Please keep discussions in English
And to translate this
Please install [Indium](https://modrinth.com/mod/indium/version/1.0.23+mc1.20.1)
And remove DashLoader as it is not compatible with Sodium 0.5.0
