### ISSUE TITLE
Crash when physics block is doing physics [1.20.1]

### ISSUE THREAD

**Issue by Zacgamingpro1234** [PepperCode1/Continuity#339]
So I was doing a build battle with my friends when they activated a piston and I crashed. Same thing happened when sand was falling.
Here's the log file:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-11-19 16:45:14
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zbm000$continuity$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zbm000$continuity$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Entity being rendered --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
	Entity ID: 1475
	Entity Name: Falling Sand
	Entity's Exact location: -4.50, -56.04, 4.50
	Entity's Block location: World: (-5,-57,4), Section: (at 11,7,4 in -1,-4,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {Air:300s,BlockState:{Name:"minecraft:sand"},CancelDrop:0b,DropItem:1b,FallDistance:0.04f,FallHurtAmount:0.0f,FallHurtMax:40,Fire:-1s,HurtEntities:0b,Invulnerable:0b,Motion:[0.0d,-0.0392d,0.0d],OnGround:0b,PortalCooldown:0,Pos:[-4.5d,-56.04d,4.5d],Rotation:[0.0f,0.0f],Time:1,UUID:[I;-1369309100,-1269677193,-1369396307,1666815846]}
	Immitating BlockState: Block{minecraft:sand}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_901@366233df
	Location: -0.82,2.37,3.74 - World: (-1,2,3), Section: (at 15,2,3 in -1,0,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Rotation: 0.0
	Delta: 0.20015538
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 3 total; [class_746['Zacgamingpro1234'/1474, l='ClientLevel', x=-3.68, y=-60.00, z=0.76], class_745['blackninja14'/1080, l='ClientLevel', x=-3.49, y=-56.44, z=18.59], class_745['ProGamer'/786, l='ClientLevel', x=1.54, y=-43.75, z=7.88]]
	Chunk stats: 145, 145
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 71344 game time, 58247 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cbh000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:11566)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/LowOnFire_1.20.1.zip, file/Tiny_Tools_1.20.zip, file/ReimaginedGUI(Dark)+1.20.zip, file/VisibleOres2.10.zip, betterbeds:fancybeds, betterbeds:fancyconnectedbeds, continuity:default, continuity:glass_pane_culling_fix, file/toteblock.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 677229464 bytes (645 MiB) / 1006632960 bytes (960 MiB) up to 3456106496 bytes (3296 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 5500
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1616
	Graphics card #0 versionInfo: DriverVersion=20.19.15.5166
	Graphics card #1 name: AMD Radeon R7 M260 Series
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x6605
	Graphics card #1 versionInfo: DriverVersion=27.20.20913.2000
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 10627.11
	Virtual memory used (MB): 7349.79
	Swap memory total (MB): 6656.00
	Swap memory used (MB): 2367.86
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3276M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		authme: Auth Me 7.0.2+1.20
		bcc: BetterCompatibilityChecker 4.0.8
		betterbeds: Better Beds 1.3.0
		betterpingdisplay: Better Ping Display 1.1.1
		boatiview: Boat Item View Fabric 0.0.5
		bsvsb: Better Sodium Video Settings Button 3.0.3
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		connectivity: Connectivity Mod 1.20.1-4.5
		continuity: Continuity 3.0.0-beta.4+1.20.1
		cupboard: cupboard 1.20.1-1.8
		dashloader: DashLoader 5.0.0-beta.2+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		dynamic_fps: Dynamic FPS 3.2.1
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		exordium: Exordium 1.1.4-mc1.20.1
		fabric-api: Fabric API 0.90.7+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.2+1bc31aeb77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		farsight: Farsight Mod 1.20.1-4.1
			org_jctools_jctools-core: jctools-core 4.0.1
		faster_entity_animations: FastAnim 1.6
		ferritecore: FerriteCore 6.0.1
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.1.1
		freecam: Freecam 1.2.1+1.20
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		lithium: Lithium 0.11.2
		malilib: MaLiLib 0.16.1
		methane: Methane 2.5.0
		minecraft: Minecraft 1.20.1
		mkb: ModernKeyBinding 1.2.0
		modmenu: Mod Menu 7.2.2
		moreculling: More Culling 1.20.1-0.19.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
			conditional-mixin: conditional mixin 0.3.2
		musicplayer: Music Player 2.7.0.235
		notenoughcrashes: Not Enough Crashes 4.4.6+1.20.1
		noxesium: Noxesium 1.0.3+9b339b0
			com_noxcrew_noxesium_api_: api 1.0.3+9b339b0
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.1-build.95
		replaymod: Replay Mod 1.20.1-2.6.13
		resourcify: Resourcify 1.2.1
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
			universalcraft: UniversalCraft 312
		rrls: Remove Reloading Screen 3.2.0-1.20.1-fabric
		serverpingerfixer: Server Pinger Fixer 1.0.3
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.2+fabric.dbc156f
		tlskincape: TLSkinCape 1.32
		uteamcore: U Team Core 5.1.4.269
		videotape: Video Tape 1.2.1
			com_github_krlite_pierced: Pierced v1.2
		wi_zoom: WI Zoom 1.5-MC1.20.1
	Launched Version: fps
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon R7 M260 Series GL version 3.2.14830 Core Profile Forward-Compatible No Error Context 22.6.1 27.20.20913.2000, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/LowOnFire_1.20.1.zip, file/Tiny_Tools_1.20.zip, file/ReimaginedGUI(Dark)+1.20.zip, file/VisibleOres2.10.zip, betterbeds:fancybeds (incompatible), betterbeds:fancyconnectedbeds (incompatible), continuity:default, continuity:glass_pane_culling_fix, file/toteblock.zip (incompatible)
	Current Language: en
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
	Client Crashes Since Restart: 6
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Continuity (continuity), Minecraft (minecraft), Fabric Loader (fabricloader), Not Enough Crashes (notenoughcrashes)

**Comment by PepperCode1** [comment]
Indium must be installed when using Sodium.

**Comment by Zacgamingpro1234** [comment]
oh thanks didn't notice that
