### ISSUE TITLE
(Crash) Tessellating block in world - Indium Renderer

### ISSUE THREAD

**Issue by minisbett** [PepperCode1/Continuity#342]
It seems like there is some issue with continuity. While walking around randomly in the world, not being able to identify anything that could specifically lead to this, my game craches. I'm using Fabric API 0.90.7, Indium 1.0.27 and Continuity 3.0.0-beta4. I'm not sure about any incompatibilities.
```
[12:59:22] [Chunk Render Task Executor #3/ERROR]: Chunk build failed
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26225()" because "$$5" is null
	at net.minecraft.class_2248.method_9607(class_2248.java:262) ~[client-intermediary.jar:?]
	at me.pepperbell.continuity.client.model.CullingCache.shouldCull(CullingCache.java:20) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at me.pepperbell.continuity.client.model.CullingCache.shouldCull(CullingCache.java:36) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.transform(CTMBakedModel.java:97) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:63) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext.renderQuad(AbstractBlockRenderContext.java:111) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext$2.emitDirectly(AbstractBlockRenderContext.java:74) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:261) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:56) ~[indium-1.0.27+mc1.20.1.jar:?]
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:65) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-38d52f0edc48f475.jar:?]
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-38d52f0edc48f475.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:53) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
```

**Comment by minisbett** [comment]
Not sure of how much help it is / whether someone can help me out here, but after uninstalling continuity I am still crashing at the same location, it's just a different error now, accordingly to the stacktrace from sodium instead of continuity this time.
```
java.lang.RuntimeException: Exception thrown while executing job
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:346)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:279)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:191)
	at net.minecraft.class_761.method_3273(class_761.java:15033)
	at net.minecraft.class_761.method_22710(class_761.java:1247)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Palette does not contain entry for value in storage
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at net.minecraft.class_3508.sodium$unpack(class_3508.java:1542)
	at net.minecraft.class_2841.sodium$unpack(class_2841.java:2037)
	at me.jellysquid.mods.sodium.client.world.WorldSlice.unpackBlockData(WorldSlice.java:187)
	at me.jellysquid.mods.sodium.client.world.WorldSlice.copySectionData(WorldSlice.java:166)
	at me.jellysquid.mods.sodium.client.world.WorldSlice.copyData(WorldSlice.java:152)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderCache.init(BlockRenderCache.java:50)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:60)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by YukiAyase** [comment]
Sending your full log instead would be better
.minecraft/logs, filename is "latest"

**Comment by minisbett** [comment]
Now I'm getting
```
The game crashed whilst encountered exception while building chunk meshes
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26225()" because "adjState" is null
```
Here's my latest.log with that error, the error doesn't seem to be specific to continuity but maybe you can help me out regardless
[latest.log](https://github.com/PepperCode1/Continuity/files/13536272/latest.log)

**Comment by minisbett** [comment]
Other people on the server seem to have the same issue, sometimes it randomly starts happening, we're trying to narrow down the location of here this happens

**Comment by minisbett** [comment]
We kind of narrowed it down to a couple chunks, it always seems to happen when chunks are initially loaded, aka. when joining the server or changing render distance which reloads all chunks

**Comment by minisbett** [comment]
I'm gonna redirect this issue to sodium

**Comment by PepperCode1** [comment]
Closing as this seems to have been resolved.
