### ISSUE TITLE
Request: update to 1.20.4

### ISSUE THREAD

**Issue by ghost** [PepperCode1/Continuity#348]
Request: update to 1.20.4

**Comment by PepperCode1** [comment]
The latest 1.20.2 release already works on 1.20.4.

**Comment by ghost** [comment]
@PepperCode1 

Time: 2023-12-13 13:06:07
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_835.handler$zzn000$continuity$beforeRenderModels(class_835.java:518)
	at net.minecraft.class_835.method_3576(class_835.java:39)
	at net.minecraft.class_835.method_3569(class_835.java:20)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.handler$bec000$nvidium$overrideEntityRenderer(SodiumWorldRenderer.java:568)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:271)
	at net.minecraft.class_761.handler$bgf000$sodium$onRenderBlockEntities(class_761.java:7831)
	at net.minecraft.class_761.method_22710(class_761.java:1146)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_835.handler$zzn000$continuity$beforeRenderModels(class_835.java:518)
	at net.minecraft.class_835.method_3576(class_835.java:39)
	at net.minecraft.class_835.method_3569(class_835.java:20)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.handler$bec000$nvidium$overrideEntityRenderer(SodiumWorldRenderer.java:568)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:271)
	at net.minecraft.class_761.handler$bgf000$sodium$onRenderBlockEntities(class_761.java:7831)
	at net.minecraft.class_761.method_22710(class_761.java:1146)
	at net.minecraft.class_757.method_3188(class_757.java:1098)

**Comment by ghost** [comment]
Is this Sodium or Continuity? I see both names

**Comment by YukiAyase** [comment]
The answer to your problem is **not having Indium installed**
And Indium hasn't been updated to the latest version of Sodium and Minecraft so we all have to wait for that

**Comment by ghost** [comment]
Alright, thank you for the quick response.
However: the recourse packs included with Continuity shows outdated. Still something thats could be updated.

**Comment by OpenBagTwo** [comment]
That's awesome that the previous version of Continuity works with 1.20.4. Can you take a minute to update the metadata on Modrinth to reflect that?

**Comment by PepperCode1** [comment]
`3.0.0-beta.4+1.20.2` has been marked as compatible with 1.20.3 and 1.20.4 on Modrinth and CurseForge.
