### ISSUE TITLE
Reload resources failed Version 3.0.0-beta.4+1.20.2

### ISSUE THREAD

**Issue by Tiegertosch** [PepperCode1/Continuity#407]
When trying to load a resource pack I get the error "Reload resources failed" and this error message in the console. I should also mention that I am trying to load the Stay True resource pack, which is not officially supported by 1.20.5

```[11:50:34] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
[B#822]  java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.materialFinder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
[B#822]  	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
[B#822]  	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
[B#822]  	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
[B#822]  	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
[B#822]  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
[B#822]  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
[B#822]  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
[B#822]  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
[B#822]  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[B#822]  Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.materialFinder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
[B#822]  	at me.pepperbell.continuity.client.util.RenderUtil.lambda$static$0(RenderUtil.java:33) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357) ~[?:?]
[B#822]  	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225) ~[?:?]
[B#822]  	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194) ~[?:?]
[B#822]  	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
[B#822]  	at me.pepperbell.continuity.client.util.RenderUtil.getMaterialFinder(RenderUtil.java:60) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at me.pepperbell.continuity.client.util.RenderUtil.findOverlayMaterial(RenderUtil.java:45) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at me.pepperbell.continuity.client.processor.overlay.StandardOverlayQuadProcessor.<init>(StandardOverlayQuadProcessor.java:65) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at me.pepperbell.continuity.client.processor.overlay.StandardOverlayQuadProcessor$Factory.createProcessor(StandardOverlayQuadProcessor.java:386) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at me.pepperbell.continuity.client.processor.overlay.StandardOverlayQuadProcessor$Factory.createProcessor(StandardOverlayQuadProcessor.java:382) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at me.pepperbell.continuity.client.processor.AbstractQuadProcessorFactory.createProcessor(AbstractQuadProcessorFactory.java:50) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at me.pepperbell.continuity.client.processor.AbstractQuadProcessorFactory.createProcessor(AbstractQuadProcessorFactory.java:14) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at me.pepperbell.continuity.client.resource.CTMPropertiesLoader$LoadingContainer.toProcessorHolder(CTMPropertiesLoader.java:109) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at me.pepperbell.continuity.client.resource.CTMPropertiesLoader$LoadingResult.createProcessorHolders(CTMPropertiesLoader.java:132) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at me.pepperbell.continuity.client.resource.BakedModelManagerReloadExtension.beforeBaking(BakedModelManagerReloadExtension.java:44) ~[CLIENT-ONLY-continuity-3.0.0-beta.4+1.20.2.jar:?]
[B#822]  	at net.minecraft.class_1092.handler$zba000$continuity$onHeadBake(class_1092.java:555) ~[client-intermediary.jar:?]
[B#822]  	at net.minecraft.class_1092.method_45883(class_1092.java) ~[client-intermediary.jar:?]
[B#822]  	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
[B#822]  	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
[B#822]  	... 6 more```

**Comment by Tiegertosch** [comment]
I also tested another resource pack with connected textures "BetterVanillaBuilding" which is officially available for 1.20.5 and I get the same error.

**Comment by YukiAyase** [comment]
Please send your full log instead located in **.minecraft/logs** with the filename **"latest"**

**Comment by Tiegertosch** [comment]
Here you go 👍🏻
[latest.log](https://github.com/PepperCode1/Continuity/files/15137831/latest.log)

**Comment by YukiAyase** [comment]
**Indium** is needed when **Sodium** is installed
But Indium has not yet updated to support 1.20.5
You'd have to wait for Indium to update
Duplicate of #107

**Comment by Tiegertosch** [comment]
Well, my bad. Totally forgot 🫠
