### ISSUE TITLE
Crashing when moving fast 1.21

### ISSUE THREAD

**Issue by MuravlevAS** [PepperCode1/Continuity#428]
installed mod version 3.0.0-beta.5+1.21 with fabric 1.21

Minecraft crashing with npe when rendering:
```
java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CtmBakedModel$CtmQuadTransform.<init>(CtmBakedModel.java:86)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
...
```

More details in crash report: [crash-2024-06-14_13.29.50-client.txt](https://github.com/user-attachments/files/15832707/crash-2024-06-14_13.29.50-client.txt)

Crash happened when I increased my speed in spectator mod.

**Comment by PepperCode1** [comment]
Indium is required when using Sodium. As Indium is not updated to 1.21 yet, wait, remove Sodium, or remove Continuity.
