### ISSUE TITLE
Placing a block that causes sand to fall causes Minecraft to crash.

### ISSUE THREAD

**Issue by ffddf111** [PepperCode1/Continuity#432]
error message

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CtmBakedModel$CtmQuadTransform.<init>(CtmBakedModel.java:86)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$znk000$continuity$beforeRenderModel(class_901.java:515)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)

-- Entity being rendered --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
	Entity ID: 469
	Entity Name: falling sand
	Entity's Exact location: 25.50, 65.96, 72.50
	Entity's Block location: World: (25,65,72), Section: (at 9,1,8 in 1,4,4; chunk contains blocks 16,-64,64 to 31,319,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Immitating BlockState: Block{minecraft:sand}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Comment by YukiAyase** [comment]
This doesn't really give us much information
Please upload your whole log file located in **.minecraft/logs**, filename is **"latest"**

**Comment by ffddf111** [comment]
[latest.log](https://github.com/user-attachments/files/15858145/latest.log)

**Comment by YukiAyase** [comment]
**Indium is required when Sodium is installed**
Indium has not yet updated to support 1.21
