### ISSUE TITLE
Crash "Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()""

### ISSUE THREAD

**Issue by RHX0R3** [PepperCode1/Continuity#440]
### Continuity 3.0.0-beta.5+1.21

```
java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
```

Please see report: [crash-2024-06-20_21.10.33-client.txt](https://github.com/user-attachments/files/15919139/crash-2024-06-20_21.10.33-client.txt)

```
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:18)
	at me.pepperbell.continuity.client.model.CtmBakedModel$CtmQuadTransform.<init>(CtmBakedModel.java:86)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zec000$continuity$beforeRenderModel(class_901.java:515)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:148)
	at net.minecraft.class_761.method_22977(class_761.java:1312)
	at net.minecraft.class_761.method_22710(class_761.java:1071)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
```

**Comment by PepperCode1** [comment]
Install Indium.
