### ISSUE TITLE
Game crashes with enchanted item in hand while opening inventory

### ISSUE THREAD

**Issue by knaughtilus** [PepperCode1/Continuity#450]
My game crashes when I open my Inventory, while having any enchanted Item selected/in my hand. Now I am a total noob when it comes to game and mod development, but while I had my suspicions, by removing and adding my mods back I found out Continuity was the culprit. You'll find the error message below:

```
[21:30:01] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
Caused by: java.lang.IllegalStateException: Not building!
	at net.minecraft.class_287.method_60802(class_287.java:76) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.method_60805(class_287.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.method_22912(class_287.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4720$class_4589.method_22912(class_4720.java:37) ~[client-intermediary.jar:?]
	at link.infra.indium.renderer.render.AbstractRenderContext.bufferQuad(AbstractRenderContext.java:119) ~[indium-1.0.33+mc1.21.jar:?]
	at link.infra.indium.renderer.render.ItemRenderContext.renderQuad(ItemRenderContext.java:177) ~[indium-1.0.33+mc1.21.jar:?]
	at link.infra.indium.renderer.render.ItemRenderContext$1.emitDirectly(ItemRenderContext.java:69) ~[indium-1.0.33+mc1.21.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:261) ~[indium-1.0.33+mc1.21.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:56) ~[indium-1.0.33+mc1.21.jar:?]
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitItemQuads(VanillaModelEncoder.java:81) ~[fabric-renderer-api-v1-3.3.0+0ae0b97dd1-6f600c7009e92b0a.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitItemQuads(FabricBakedModel.java:128) ~[fabric-renderer-api-v1-3.3.0+0ae0b97dd1-6f600c7009e92b0a.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitItemQuads(ForwardingBakedModel.java:56) ~[fabric-renderer-api-v1-3.3.0+0ae0b97dd1-6f600c7009e92b0a.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitItemQuads(EmissiveBakedModel.java:104) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:129) ~[indium-1.0.33+mc1.21.jar:?]
	at net.minecraft.class_918.handler$bcb000$indium$hook_renderItem(class_918.java:1052) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_23179(class_918.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_23177(class_918.java:260) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3233(class_759.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_989.method_4192(class_989.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_5697.method_4192(class_5697.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_989.method_17162(class_989.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_989.method_4199(class_989.java:15) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:148) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_29977(class_490.java:155) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:720) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_48472(class_490.java:155) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_2486(class_490.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_2389(class_490.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25420(class_465.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25394(class_437.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:100) ~[client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25394(class_490.java:81) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$method_47413$240(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$bbc000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
	... 6 more
[21:30:02] [Server thread/INFO]: Stopping server
[21:30:02] [Server thread/INFO]: Saving players
[21:30:02] [Server thread/INFO]: PlayernameReplaced lost connection: Disconnected
[21:30:02] [Server thread/INFO]: PlayernameReplaced left the game
[21:30:02] [Server thread/INFO]: Stopping singleplayer server as player logged out
[21:30:02] [Server thread/INFO]: Saving worlds
[21:30:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Testing]'/minecraft:overworld
[21:30:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Testing]'/minecraft:the_nether
[21:30:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Testing]'/minecraft:the_end
[21:30:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (Testing): All chunks are saved
[21:30:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:30:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:30:02] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
```

A fix for this would be greatly appreciated. If you need any further information let me know.

**Comment by PepperCode1** [comment]
This is an Iris issue that has been fixed but a release with said fix has not been made yet.

**Comment by knaughtilus** [comment]
Oh, I'm sorry. Thanks for the info.
