### ISSUE TITLE
Glass Plane Culling Fix & Default Connected Textures Error

### ISSUE THREAD

**Issue by chronality** [PepperCode1/Continuity#487]
Description: Tessellating block in world - Indium Renderer

java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$zpc000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	
I've heard the downgrading the Fabric API helps with the this issue, however I have a world that must be 1.21 using the new version of Fabric API for 1.21. When trying to use Glass Plane Culling Fix & Default Connected Textures Error my game crashes. When will we be expecting a fix for the users who are running the newer version of Fabric API? Also wondering if there is any other texture packs that give off the same effect.
![Screenshot 2024-08-05 211423](https://github.com/user-attachments/assets/5dea0376-3c73-4ff1-8a12-61805613a109)

**Comment by akky-mc** [comment]
I'm having the exact same issue and error code. As soon as I turn off connected textures the game works fine but, as you know, half of the blocks stop working correctly.

**Comment by PepperCode1** [comment]
Downgrade Fabric API to 0.100.8; comp500/Indium#324

**Comment by chronality** [comment]
> I'm having the exact same issue and error code. As soon as I turn off connected textures the game works fine but, as you know, half of the blocks stop working correctly.

I solved the issue! Removing the indium mod should stop this crashing. At least thats what worked for me.

**Comment by chronality** [comment]
> I'm having the exact same issue and error code. As soon as I turn off connected textures the game works fine but, as you know, half of the blocks stop working correctly.

Nevermind... I does stop the crashing however the glass will not connect or any of the other blocks with indium supposedly.
