### ISSUE TITLE
The Connection Texture fail when using 1.20.1 With Continuity 3.0.0 , Indium 1.0.34 and Sodium 0.5.11

### ISSUE THREAD

**Issue by xxsTeamJJBya** [PepperCode1/Continuity#493]

**Comment by esuity** [comment]
I used 1,21 and the game crashed.

**Comment by T1nkiePlayz** [comment]
I am experiencing this issue too, when i attempt to connect to minecraft world.

**Comment by PepperCode1** [comment]
This is not enough information. Send your game log.

**Comment by albertdan128** [comment]
i also commented the same thing, and i think 1.20.1 continuity is a bit bugged cause a week ago i changed to 1.20.4 (for the tick command) and when i load in the resource pack, it doesnt crash this time

**Comment by PepperCode1** [comment]
I remember, but I need the game log that contains the crash, otherwise I can't do anything about the issue or tell you why it happens.

**Comment by ben-gineer** [comment]
Does this help?

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-08-10 09:17:23
Description: Tessellating block in world - Indium Renderer

java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$zno000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)

-- Block being tessellated --
Details:
	Block: Block{minecraft:purple_carpet}
	Block location: World: (-447,64,-720), Section: (at 1,0,0 in -28,4,-45; chunk contains blocks -448,-64,-720 to -433,319,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
Stacktrace:
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$zno000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Block being rendered --
Details:
	Block: Block{minecraft:purple_carpet}
	Block location: World: (-447,64,-720), Section: (at 1,0,0 in -28,4,-45; chunk contains blocks -448,-64,-720 to -433,319,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
	Chunk section: RenderSection at chunk (-28, 4, -45) from (-448, 64, -720) to (-433, 79, -705)
	Render context volume: class_3341{minX=-450, minY=62, minZ=-722, maxX=-431, maxY=81, maxZ=-703}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Uptime --
Details:
	JVM uptime: 32.803s
	Wall uptime: 22.459s
	High-res time: 21.138s
	Client ticks: 210 ticks / 10.500s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['benginears'/41, l='ClientLevel', x=-435.73, y=79.35, z=-719.19]]
	Chunk stats: 1024, 230
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,92,-64), Section: (at 0,12,0 in 4,5,-4; chunk contains blocks 64,-64,-64 to 79,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 40296058 game time, 315 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 1

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, caffeineconfig, continuity, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, indium, iris, journeymap, modmenu, reeses-sodium-options, sodium, sodium-extra, continuity:default, continuity:glass_pane_culling_fix, file/Better-Leaves-8.0-1.20+.zip

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Mac OS X (x86_64) version 13.6.8
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 244991144 bytes (233 MiB) / 805306368 bytes (768 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Radeon Pro 580
	Graphics card #0 vendor: AMD (0x1002)
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: Revision ID: 0x00c0, ROM Revision: 113-D000AA-931, VBIOS Version: 113-D0001A1X-025, EFI Driver Version: 01.00.931
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4 SO-DIMM
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4 SO-DIMM
	Memory slot #2 capacity (MiB): 4096.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4 SO-DIMM
	Memory slot #3 capacity (MiB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4 SO-DIMM
	Virtual memory max (MiB): 40960.00
	Virtual memory used (MiB): 14253.60
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 93231.19, total: 819207.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 93231.19, total: 819207.00
	Space in storage for io.netty.native.workdir (MiB): available: 93231.19, total: 819207.00
	Space in storage for java.io.tmpdir (MiB): available: 93231.19, total: 819207.00
	Space in storage for workdir (MiB): available: 93231.19, total: 819207.00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		continuity: Continuity 3.0.0-beta.5+1.21
		fabric-api: Fabric API 0.102.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b55973446a
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc6a
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a76a
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c6a
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a76a
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c6a
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b36a
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b55973446a
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5b6a
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c66a
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a76a
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+1daea2156a
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae256a
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b996a
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b996a
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae066a
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd96a
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc9216a
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+780172706a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a76a
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b36a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a56a
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a56a
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c6a
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b6a
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b6a
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a936a
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c6a
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+650897126a
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b6a
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c6a
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c6a
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b36a
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e6a
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea2156a
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b36a
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd06a
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b16a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b55973446a
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b55973446a
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c6a
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd3436a
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea2156a
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		indium: Indium 1.0.34+mc1.21
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		journeymap: Journeymap 1.21-6.0.0-beta.18
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.11-1.21
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21-SNAPSHOT
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
	Loaded Shaderpack: BSL_v8.2.09.zip
		Profile: HIGH (+0 options changed by user)
	Launched Version: fabric-loader-0.16.0-1.21.1
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon Pro 580 OpenGL Engine GL version 4.1 ATI-4.14.1, ATI Technologies Inc.
	Window size: 1708x960
	GFLW Platform: cocoa
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 10/12 chunks
	Resource Packs: vanilla, fabric, caffeineconfig, continuity, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, indium, iris, journeymap, modmenu, reeses-sodium-options, sodium, sodium-extra, continuity:default, continuity:glass_pane_culling_fix, file/Better-Leaves-8.0-1.20+.zip
	Current Language: en_gb
	Locale: en_GB
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
```

**Comment by PepperCode1** [comment]
No, if you are not running exactly 1.20.1, the log or any other information will not help. It is a separate issue.

**Comment by ben-gineer** [comment]
Apologies - I read the title as 1.21.1, not 1.20.1

**Comment by Grandev-0** [comment]
I have the same issue and it has something to do with BakedModel because I have this issue on 1.21 and I think it could be a fabric API issue since this wasn't the only mod that caused it from me [this](https://www.curseforge.com/minecraft/mc-mods/super-better-grass) one did as well with the same error including BakedModel and it started when I updated fabric api

**Comment by xxsTeamJJBya** [comment]
The question solved with 
![image](https://github.com/user-attachments/assets/1ff6664f-d9b7-4437-b648-772c4c68e241)
this Resorece Pack. I forgot to add it.

**Comment by xxsTeamJJBya** [comment]
thx for all people help me

**Comment by xxsTeamJJBya** [comment]
Recourse Pack not Resorece Pack sry
