### ISSUE TITLE
Confusing "incompatible mods found" error message

### ISSUE THREAD

**Issue by spicylambliver** [PepperCode1/Continuity#569]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Continuity' (continuity) 3.0.0+1.21.3 with any version that is compatible with:
		 - sodium 0.6.0+mc1.21.3
More details:
	 - Mod 'Continuity' (continuity) 3.0.0+1.21.3 is incompatible with any version before 0.6.2 of mod 'Sodium' (sodium), but a matching version is present: 0.6.0+mc1.21.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

So it says that continuity is compatible with sodium 0.6.0+mc1.21.3 which is the version I currently have, but it's still giving me an error ;-;

**Comment by YukiAyase** [comment]
It says its **incompatible** with any version of Sodium before 0.6.2
Try and update Sodium

**Comment by spicylambliver** [comment]
oh, I'm dumb lol, thanks :3
