### ISSUE TITLE
IDK why not Connecting (1.18.2)

### ISSUE THREAD

**Issue by footballs-w-edits** [PepperCode1/Continuity#68]
Why in the world does Continuity not connect the glass or anything? It was working before, why not now? Is it because Continuity isn't compatible with Fabric API 0.47.10 (Latest)?

**Comment by PepperCode1** [comment]
It is compatible, as that's the version I used while developing. Send a log file so I can debug this issue.

**Comment by footballs-w-edits** [comment]
Mods:
  [✔️] appleskin-fabric-mc1.18.1-2.3.0
  [✔️] cem-0.7.0
  [✔️] cloth-config-6.2.57-fabric
  [✔️] completeconfig-lib-1.3.3
  [✔️] continuity-1.1.0+1.18.2
  [✔️] eating-animation-1.5
  [✔️] entityculling-fabric-mc1.18-1.5.0
  [✔️] fabric-api-0.47.10+1.18.2
  [✔️] fabric-carpet-1.18.2-1.4.66+v220228
  [✔️] ferritecore-4.2.0-fabric
  [✔️] indium-1.0.2+mc1.18.2
  [✔️] iris-mc1.18.2-1.2.1
  [✔️] lambdynamiclights-2.1.0+1.17
  [✔️] lazydfu-0.1.2
  [✔️] litematica-fabric-1.18.2-0.11.0
  [✔️] lithium-fabric-mc1.18.2-0.7.9
  [✔️] malilib-fabric-1.18.2-0.12.0
  [✔️] minihud-fabric-1.18.2-0.22.0
  [✔️] modmenu-3.1.0
  [✔️] okzoomer-5.0.0-beta.4+1.18.2
  [✔️] PresenceFootsteps-1.5.0
  [✔️] reeses_sodium_options-mc1.18.2-1.4.1
  [✔️] sit-1.18.2-17
  [✔️] sodium-extra-mc1.18.2-0.4.1
  [✔️] sodium-fabric-mc1.18.2-0.4.1+build.15
  [✔️] starlight-1.0.2+fabric.89b8d9f

[20:06:36] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[20:06:36] [main/INFO]: Loading 83 mods:
	- appleskin 2.3.0+mc1.18.1
	- caffeineconfig 1.0.0 via sodium-extra
	- carpet 1.4.66
	- cem 0.7.0
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- completeconfig 1.3.3
	- continuity 1.1.0+1.18.2
	- eatinganimationid 1.5
	- entityculling 1.5.0
	- fabric 0.47.10+1.18.2
	- fabric-api-lookup-api-v1 1.5.6+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.2+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.11+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.8+d7c144a860 via fabric
	- fabric-commands-v0 0.2.7+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.20+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.1+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.10+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.16+2540745460 via fabric
	- fabric-entity-events-v1 1.4.7+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.18+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.12+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.12+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.2+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.9+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.11+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.9+b4f4f6cd60 via fabric
	- fabric-loot-tables-v1 1.0.10+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.3+d1027f7d60 via fabric
	- fabric-models-v0 0.3.5+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.20+d882b91560 via fabric
	- fabric-networking-v0 0.3.7+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.2+34b2a0ce60 via fabric
	- fabric-particles-v1 0.2.11+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.7+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.12+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.16+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.6+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.1+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.6+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.1+d1027f7d60 via fabric
	- fabric-screen-api-v1 1.0.9+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.13+d7c144a860 via fabric
	- fabric-textures-v0 1.0.11+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.13+cca23f9360 via fabric
	- fabricloader 0.13.3
	- ferritecore 4.2.0
	- indium 1.0.2+mc1.18.2
	- iris 1.2.1
	- java 17
	- kirin 1.10.0 via presencefootsteps
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- libzoomer 0.4.0+1.18.2 via okzoomer
	- litematica 0.11.0
	- lithium 0.7.9
	- malilib 0.12.0
	- minecraft 1.18.2
	- minihud 0.22.0
	- modmenu 3.1.0
	- okzoomer 5.0.0-beta.4+1.18.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_quiltmc_quilt-json5 1.0.0 via okzoomer
	- presencefootsteps 1.5.0
	- pride 1.1.0+1.17 via lambdynlights
	- quilt_base 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-api-base
	- quilt_lifecycle_events 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-lifecycle-events-v1
	- quilt_resource_loader 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-resource-loader-v0
	- quilt_tags 1.0.0+1.18.2-SNAPSHOT via okzoomer
	- quilted-fabric-api-base 1.0.0+1.18.2-SNAPSHOT via okzoomer
	- quilted-fabric-lifecycle-events-v1 2.0.1+1.18.2-SNAPSHOT via okzoomer
	- quilted-fabric-resource-loader-v0 1.0.1+1.18.2-SNAPSHOT via okzoomer
	- reeses-sodium-options 1.4.1
	- sit 1.18.2-17
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.1
	- spruceui 3.3.0+1.17 via lambdynlights
	- starlight 1.0.2+fabric.89b8d9f
[20:06:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/gauravbhasin/Library/Application%20Support/ManyMC/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:06:36] [main/INFO]: Compatibility level set to JAVA_16
[20:06:36] [main/INFO]: Compatibility level set to JAVA_17
[20:06:36] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 1 override(s) found
[20:06:36] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[20:06:36] [main/INFO]: Loaded configuration file for Sodium Extra: 25 options available, 0 override(s) found
[20:06:36] [main/WARN]: Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
[20:06:36] [main/WARN]: Error loading class: link/infra/indium/renderer/render/AbstractQuadRenderer (java.lang.ClassNotFoundException: link/infra/indium/renderer/render/AbstractQuadRenderer)
[20:06:36] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[20:06:36] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[20:06:39] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$ccg000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[20:06:39] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[20:06:40] [Render thread/INFO]: sodium-extra.mixins.json:gui.MinecraftClientAccessor->@Accessor[FIELD_GETTER]::getCurrentFPS()I should be static as its target is
[20:06:40] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:06:41] [Render thread/INFO]: Setting user: PTCSMMaster
[20:06:41] [Render thread/INFO]: Loading 61 entities from Custom Entity Models 0.7.0
[20:06:41] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[20:06:41] [Render thread/INFO]: [LambDynLights] Initializing LambDynamicLights...
[20:06:41] [Render thread/INFO]: [LambDynLights] Configuration loaded.
[20:06:42] [Render thread/INFO]: Backend library: LWJGL version 3.3.0 build 21
[20:06:43] [Render thread/WARN]: Shaders are disabled because enableShaders is set to false in iris.properties
[20:06:43] [Render thread/WARN]: Shaders are disabled
[20:06:43] [Render thread/WARN]: Hardware information:
[20:06:43] [Render thread/WARN]: CPU: 8x Apple M1
[20:06:43] [Render thread/WARN]: GPU: Apple M1 (Supports OpenGL 4.1 Metal - 76.3)
[20:06:43] [Render thread/WARN]: OS: Mac OS X (12.2.1)
[20:06:43] [Render thread/WARN]: Method overwrite conflict for getNativeMemoryUsage in sodium.mixins.json:features.debug.MixinDebugHud, previously written by net.coderbot.iris.mixin.MixinDebugScreenOverlay. Skipping method.
[20:06:44] [Render thread/INFO]: Reloading ResourceManager: Default (AppleSkin, CaffeineConfig, Carpet Mod, Custom Entity Models, Cloth Config v6, CompleteConfig, Continuity, Eating Animation, EntityCulling-Fabric, Fabric API, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Loader, Indium, Iris, LambDynamicLights, LazyDFU, LibZoomer, Litematica, Lithium, MaLiLib, MiniHUD, Mod Menu, Ok Zoomer, Presence Footsteps, Pride Lib, Quilt Base API, Quilt Lifecycle Events, Quilt Resource Loader, Quilt Tags API, Quilted Fabric API Base, Quilted Fabric Lifecycle Events (v1), Quilted Fabric Resource Loader (v0), Reese's Sodium Options, Sit, Sodium, Sodium Extra, SpruceUI, Starlight), BetterVanillaAnimals_v1.8.7, FreshAnimations_v1.5, VanillaTweaks_r120524, VanillaTweaks_r158373, VanillaTweaks_r138102, VanillaTweaks_r228166, VanillaTweaks_r353401, VanillaTweaks_r424266, VanillaTweaks_r429791, VanillaTweaks_r457041, VanillaTweaks_r542554, VanillaTweaks_r564453, VanillaTweaks_r746108, VanillaTweaks_r836330, VanillaTweaks_r529796, continuity/glass_pane_culling_fix, continuity/default
[20:06:44] [Render thread/INFO]: [Ok Zoomer] →w→ what's this
[20:06:46] [Render thread/INFO]: OpenAL initialized on device CoreAudio Default
[20:06:46] [Render thread/INFO]: Sound engine started
[20:06:46] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[20:06:46] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[20:06:46] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:06:46] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:06:46] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:06:46] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:06:46] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/bat.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/blaze.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/cat.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/cave_spider.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/chicken.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/cow.jem
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/creeper.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/dolphin.jem
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/dolphin.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Entity "minecraft:dolphin" is unsupported!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/drowned.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/elder_guardian.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/enderman.jem
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/evoker.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/fox.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/giant.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/goat.jem
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/goat.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Entity "minecraft:goat" is unsupported!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/guardian.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/husk.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/illusioner.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/iron_golem.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/llama.jem
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/llama.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Entity "minecraft:llama" is unsupported!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/llama_decor.jem
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/llama_decor.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Unknown object "llama_decor"!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/mooshroom.jem
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/ocelot.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/phantom.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/pig.jem
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/pillager.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/rabbit.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/ravager.jem
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/ravager.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Entity "minecraft:ravager" is unsupported!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/sheep.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/sheep_wool.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/silverfish.jem
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/silverfish.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Entity "minecraft:silverfish" is unsupported!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/skeleton.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/spider.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/stray.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/trader_llama.jem
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/trader_llama.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Entity "minecraft:trader_llama" is unsupported!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/trader_llama_decor.jem
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/trader_llama_decor.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Unknown object "trader_llama_decor"!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/turtle.jem
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/turtle.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Entity "minecraft:turtle" is unsupported!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/vex.jem
[20:06:46] [Render thread/ERROR]: Error parsing minecraft:optifine/cem/vex.jem:
[20:06:46] [Render thread/ERROR]: java.lang.Exception: Entity "minecraft:vex" is unsupported!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/villager.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/vindicator.jem
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/WARN]: 	the above file didn't specify all uv directions!
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/wandering_trader.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/witch.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/wolf.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/zombie.jem
[20:06:46] [Render thread/INFO]: minecraft:optifine/cem/zombie_villager.jem
[20:06:46] [Render thread/WARN]: Model part left_shoulder isn't specified in optifine/cem/evoker.jem
[20:06:46] [Render thread/WARN]: Model part left_shoulder isn't specified in optifine/cem/vindicator.jem
[20:06:46] [Render thread/WARN]: Model part right_ear isn't specified in optifine/cem/fox.jem
[20:06:46] [Render thread/WARN]: Model part left_ear isn't specified in optifine/cem/fox.jem
[20:06:46] [Render thread/WARN]: Model part nose isn't specified in optifine/cem/fox.jem
[20:06:46] [Render thread/WARN]: Model part right_horn isn't specified in optifine/cem/cow.jem
[20:06:46] [Render thread/WARN]: Model part left_horn isn't specified in optifine/cem/cow.jem
[20:06:46] [Render thread/WARN]: Model part arms isn't specified in optifine/cem/pillager.jem
[20:06:46] [Render thread/WARN]: Model part left_shoulder isn't specified in optifine/cem/pillager.jem
[20:06:46] [Render thread/WARN]: Model part arms isn't specified in optifine/cem/pillager.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "torad(10)+sin(age/60*pi*2)/40+clamp(torad(5)*limb_speed,torad(-45),torad(50))+(sin(pi*swing_progress)/3)" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "if(is_riding,0,clamp(torad(-15)+limb_speed,torad(-15),if(right_arm.rx<torad(-50),torad(15),0)))+sin(torad(180)+limb_swing/1.5)/3*limb_speed+(head_yaw/57.5)/6+(sin(-pi*swing_progress))" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "head.rz+if(is_riding,0,clamp(torad(-2)+limb_speed,torad(-2),if(right_arm.rx<torad(-50),torad(2),0)))+sin(age/80*pi*2)/40-sin(age/80*pi*2-torad(90))/20-(head_yaw/57.5)/4-sin(age/4*pi*2)/80-(sin(pi*swing_progress)/3)" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "head.tx" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "head.ty+if(is_in_lava,-sin(age/60*pi*2)/4,0)" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "head.tz" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "-5+body.tx-(head_yaw/57.5)/2+(sin(pi*swing_progress)*2)" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "5+body.tx+(head_yaw/57.5)/2-(sin(pi*swing_progress)*2)" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "if(is_in_lava,1,2.5)+sin(age/60*pi*2-torad(60))/5+body.ty" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/ERROR]: Error applying animation "if(is_in_lava,1,2.5)+sin(age/60*pi*2-torad(60))/5+body.ty" in "optifine/cem/wither_skeleton.jem":
[20:06:46] [Render thread/ERROR]: Model part body isn't specified in optifine/cem/wither_skeleton.jem
[20:06:46] [Render thread/WARN]: Model part headwear2 isn't specified in optifine/cem/zombie_villager.jem
[20:06:46] [Render thread/WARN]: Model part nose isn't specified in optifine/cem/zombie_villager.jem
[20:06:46] [Render thread/WARN]: Model part headwear2 isn't specified in optifine/cem/zombie_villager.jem
[20:06:46] [Render thread/WARN]: Model part left_shoulder isn't specified in optifine/cem/illusioner.jem
[20:06:47] [Render thread/WARN]: Model part right_horn isn't specified in optifine/cem/mooshroom.jem
[20:06:47] [Render thread/WARN]: Model part left_horn isn't specified in optifine/cem/mooshroom.jem
[20:06:47] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[20:06:47] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:06:47] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:06:47] [Render thread/INFO]: Skipping non-result value minecraft:lantern=UNASSIGNED
[20:06:47] [Render thread/INFO]: Skipping non-result value minecraft:soul_lantern=UNASSIGNED
[20:06:53] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:06:53] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:06:53] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:06:53] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:06:53] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:06:53] [Render thread/INFO]: Loaded 7 recipes
[20:06:53] [Render thread/WARN]: Found validation problem in {minecraft:entities/ender_dragon}.pools[0].entries[0]: Unknown loot table called minecraft:entities/reference/extra/ender_dragon
[20:06:53] [Render thread/WARN]: Found validation problem in {minecraft:entities/shulker}.pools[2].entries[0]: Unknown loot table called minecraft:entities/reference/extra/shulker
[20:06:53] [Render thread/INFO]: Loaded 1146 advancements
[20:06:53] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', 
[20:06:56] [pool-2-thread-3/WARN]: Failed fetching news from Realms, falling back to local cache
net.minecraft.class_4355: Could not connect to Realms: Read timed out
	at net.minecraft.class_4341.method_20998(class_4341.java:438) ~[client-intermediary.jar:?]
	at net.minecraft.class_4341.method_21032(class_4341.java:371) ~[client-intermediary.jar:?]
	at net.minecraft.class_4360.method_33417(class_4360.java:258) ~[client-intermediary.jar:?]
	at net.minecraft.class_4360.method_33416(class_4360.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.class_5784.run(class_5784.java:32) [client-intermediary.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

Not a file, but the log itself. Hope you can fix the issue.

Maybe Indium is the issue, exploring the log a little more?

**Comment by PepperCode1** [comment]
This is a new incompatibility with Quilted Fabric API, which Ok Zoomer bundles. I am currently trying to resolve this.

**Comment by footballs-w-edits** [comment]
Once done, please inform me on Github and upload to CurseForge. I don't have access to discord.

**Comment by PepperCode1** [comment]
From the Discord announcements channel:

> There have been numerous reports of Continuity not working in 1.18.2. This is due to a new incompatibility with Quilt Standard Libraries, which mods such as Ok Zoomer and Inspecio bundle.
> **Specific Issue**
> Having QSL installed alongside Continuity disables functionality of the default pack for default textures.
> **What is being done to solve this?**
> I have conversed with the developers of QSL and I reached the conclusion that **using Quilt Standard Libraries alongside Continuity is not supported**. Neither I nor the developers of QSL will address the incompatibility because QSL on Fabric itself will soon be unsupported, as stated by the developers of QSL.
> **What can users do?**
> Here are some possible solutions:
> - Uninstall mods that bundle QSL.
> - Downgrade mods that bundle QSL to a version in which QSL is not utilized.
> - Use the programmer art resource pack. Connected textures for programmer art textures still work.
> - Use an external resource pack that adds connected textures.

**Comment by MattElek** [comment]
QSL seems to have fixed the issue on its own side with PR https://github.com/QuiltMC/quilt-standard-libraries/pull/93. The latest version of inspecio [bundles the fix](https://github.com/EnnuiL/OkZoomer/issues/57#issuecomment-1085034924), [ok zoomer](https://github.com/EnnuiL/OkZoomer/issues/57#issuecomment-1085034924) is likely to follow soon.
