### ISSUE TITLE
1.18.2 immediately crashes after

### ISSUE THREAD

**Issue by ryanccn** [PepperCode1/Continuity#73]
Crash report:

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 3/18/22, 11:12 PM
Description: Unexpected error

java.lang.IncompatibleClassChangeError: Found interface net.minecraft.class_5455, but class was expected
	at me.pepperbell.continuity.client.util.biome.BiomeHolderManager.refreshHolders(BiomeHolderManager.java:41)
	at me.pepperbell.continuity.client.util.biome.BiomeHolderManager.setup(BiomeHolderManager.java:32)
	at me.pepperbell.continuity.client.handler.ClientPlayJoinHandler.onPlayReady(ClientPlayJoinHandler.java:12)
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents.lambda$static$2(ClientPlayConnectionEvents.java:53)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.onServerReady(ClientPlayNetworkAddon.java:67)
	at net.minecraft.class_634.handler$zej000$handleServerPlayReady(class_634.java:2427)
	at net.minecraft.class_634.method_11120(class_634.java:395)
	at net.minecraft.class_2678.method_11567(class_2678.java:83)
	at net.minecraft.class_2678.method_11054(class_2678.java:19)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1085)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.client.util.biome.BiomeHolderManager.refreshHolders(BiomeHolderManager.java:41)
	at me.pepperbell.continuity.client.util.biome.BiomeHolderManager.setup(BiomeHolderManager.java:32)
	at me.pepperbell.continuity.client.handler.ClientPlayJoinHandler.onPlayReady(ClientPlayJoinHandler.java:12)
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents.lambda$static$2(ClientPlayConnectionEvents.java:53)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.onServerReady(ClientPlayNetworkAddon.java:67)
	at net.minecraft.class_634.handler$zej000$handleServerPlayReady(class_634.java:2427)
	at net.minecraft.class_634.method_11120(class_634.java:395)
	at net.minecraft.class_2678.method_11567(class_2678.java:83)
	at net.minecraft.class_2678.method_11054(class_2678.java:19)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)

-- Affected level --
Details:
	All players: 1 total; [class_746['RyanCaoDev'/210, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 1024, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Default-Dark-Mode-1.18-(v1.3.1), Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (aarch64) version 12.3
	Java Version: 17.0.2, Homebrew
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Homebrew
	Memory: 2877533568 bytes (2744 MiB) / 3623878656 bytes (3456 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 17408.00
	Virtual memory used (MB): 9410.42
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 29.25
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx8192m
	Fabric Mods: 
		continuity: Continuity 1.1.0+1.18
		fabric: Fabric API 0.47.10+1.18.2
		fabric-api-base: Fabric API Base 0.4.3+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.6+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.2+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.11+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.8+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.7+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.20+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.1+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.10+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.16+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.7+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.18+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.12+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.12+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.2+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.9+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.11+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.9+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.1+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.10+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.3+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.5+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.20+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.7+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.2+34b2a0ce60
		fabric-particles-v1: Fabric Particles (v1) 0.2.11+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.7+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.12+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.16+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.6+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.1+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.1+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.17+801ec85b60
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.9+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.13+d7c144a860
		fabric-textures-v0: Fabric Textures (v0) 1.0.11+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.13+cca23f9360
		fabricloader: Fabric Loader 0.13.3
		ferritecore: FerriteCore 4.2.0
		indium: Indium 1.0.2+mc1.18.2
		java: OpenJDK 64-Bit Server VM 17
		lambdabettergrass: LambdaBetterGrass 1.2.3+1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.9
		malilib: MaLiLib 0.12.0
		minecraft: Minecraft 1.18.2
		minihud: MiniHUD 0.22.0
		modmenu: Mod Menu 3.1.0
		org_joml_joml: joml 1.10.2
		pride: Pride Lib 1.1.0+1.17
		sodium: Sodium 0.4.1+build.15
		spruceui: SpruceUI 3.3.3+1.18
		starlight: Starlight 1.0.2+fabric.89b8d9f
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.3.0 build 21
	Backend API: Apple M1 GL version 4.1 Metal - 76.3, Apple
	Window size: 1708x960
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: vanilla, file/Default-Dark-Mode-1.18-(v1.3.1), Fabric Mods
	Current Language: English (US)
	CPU: 8x Apple M1
	Server Running: true
	Player Count: 1 / 8; [class_3222['RyanCaoDev'/210, l='ServerLevel[New World]', x=-21.50, y=69.00, z=102.50]]
	Data Packs: vanilla
	World Generation: Stable
```

**Comment by ryanccn** [comment]
Would it be related to the fact that I'm using a custom LWJGL native?

**Comment by PepperCode1** [comment]
No, it's because you are using the 1.18 version of Continuity on 1.18.2. Update to the 1.18.2 version.

**Comment by ryanccn** [comment]
Oh, I see 😅 I just upgraded and forgot

**Comment by ryanccn** [comment]
Sorry for the inconvenience
